version: '2'
services:
    magiclink-app:
        image: magiclink
        external_links:
            - magiclink-mysql:mysql
            - magiclink-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/magiclink?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    magiclink-mysql:
        extends:
            file: mysql.yml
            service: magiclink-mysql
    magiclink-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: magiclink-elasticsearch
